name: Build Executables with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        python -m PyInstaller --onefile --name=TiebaScraper .\cli_entry.py

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: /src/dist